### ISSUE TITLE
mobx-router5/react-mobx-router5 differences - discussion

### ISSUE THREAD

**Issue by LeonardoGentile** [pzmosquito/mr-router5#1]
Let's continue the discussione from [here](https://github.com/router5/router5/commit/569104c7d0ce65ad8c0ac478eca5c6f03d97cdf0#commitcomment-32722652).

👍 I tough it could be more productive to join ideas/forces. If you feel your alternative is lighter and  for different use-cases maybe you could highlight these differences in your readme to avoid confusion?

> I didn't carry any of the react-router5 features into the package

I see, so either I've missed something or your 'component' property in routes definitions does nothing, isn't it? 🤔

**Comment by pzmosquito** [comment]
definitely, I'll put in some more description to avoid the confusion.

the component field is for a utility function to know which view component to render when the node is to be activated. I use MobX to management states, it doesn't have anything to do with React.

**Comment by LeonardoGentile** [comment]
> the component field is for a utility function to know which view component to render when the node is to be activated

Yes I know, I've created the idea [here](https://github.com/LeonardoGentile/react-mobx-router5#routes-configuration) but  I don't see this utility function in your code. How do you use this?

**Comment by pzmosquito** [comment]
This [utility function](https://github.com/pzmosquito/mr-router5/blob/dccc4f8d1b2ee1cd19c2dec9e06a1b563ab8b0f3/package/src/RouterStore.js#L57) is to get the route object in the routes definition. And the component field being used in [here](https://github.com/pzmosquito/mr-router5/blob/dccc4f8d1b2ee1cd19c2dec9e06a1b563ab8b0f3/package/src/index.js#L18)

**Comment by LeonardoGentile** [comment]
ok thanks, keep going 👍
